notifications:
	email: true

language: node_js
node_js: 
	- '0.10'

webhooks:
	urls:
		- 'https://webhooks.gitter.im/e/c643363401320bfde591'
		on_success: change  # options: [always|never|change] default: always
		on_failure: always  # options: [always|never|change] default: always
		on_start: false     # default: false



